### ISSUE TITLE
pip install and documentação

### ISSUE THREAD

**Issue by psnma** [iugu/iugu-python#1]
Poderia ter a opção de instalar através de `pip install iugu-py` e criar uma documentação no http://readthedocs.org

**Comment by Arenhardt** [comment]
Já é possível instalar via pip: `pip install iugu` [1].
A parte de documentação realmente é uma necessidade, assim como criação de excessões específicas e outras coisas que podem ser implementadas.

[1] https://pypi.python.org/pypi/iugu/0.1.2
