### ISSUE TITLE
Metodo request_verification da classe Marketplace exige parâmetro que não é obrigatório

### ISSUE THREAD

**Issue by JoabMendes** [iugu/iugu-python#12]
Segundo a [documentação](https://dev.iugu.com/reference#enviar-verificação-de-conta) da verificação de subcontas e o contato que tive com suporte, o parâmetro `files` não é obrigatório, porém o método atual faz a verificação do campo e levanta a exceção `RequiredParameters` caso ele não esteja presente na requisição.

https://github.com/iugu/iugu-python/blob/ae02a438bfbc7feb92ac3add3cf951fd8b92f935/iugu/marketplace.py#L18-L19

Acho interessante remover essa verificação por tanto 😉

**Comment by Arenhardt** [comment]
Boa @JoabMendes, vou fazer a correção aqui e já recriar o pacote!

Abraços!

**Comment by 0xLuz** [comment]
Show! fico no aguardo 🚀 Você vai colocar no pypi a nova versão tbm?

**Comment by 0xLuz** [comment]
Vi aqui que já atualizou no pip haha, vlw!
